[Settings]
  ID = "8195896c-7e6c-445b-a983-f16d42a19364"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  command = "npm run build"
  publish = "build"
  
[context.production.environment]
    ACCESS_TOKEN = "d87cade6c7740e2b160f08df93bcde899dfcff6800b6b5188f27124aff2fc668"

[context.deploy-preview]
  command = "npm run build-preview"